---
name: Test Python and SonarQube Scan
description: Runs pytest and SonarQube scan on the codebase.

inputs:
  aws_region:
    description: AWS region to deploy
    required: false
    default: us-east-1

  sonar_token:
    description: SonarQube Token
    required: true

  machine_user_pat:
    description: Github Catena Machine User Personal Access Token (PAT)
    required: true

  directory:
    description: Directory to run the tests. Useful for monorepos when there are multiple projects and tests.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Set Up Environment and load Cached Dependencies
      uses: catenaclearing/catena-actions/composite/setup-python@v0
      with:
        machine_user_pat: ${{ inputs.machine_user_pat }}
        directory: ${{ inputs.directory }}

    - name: Pytest
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        poetry run python -m pytest
      env:
        AWS_DEFAULT_REGION: ${{ inputs.aws_region }}

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}

    # - name: SonarQube Quality Gate check
    #   id: sonarqube-quality-gate-check
    #   uses: SonarSource/sonarqube-quality-gate-action@v1
    #   env:
    #     SONAR_TOKEN: ${{ inputs.sonar_token }}
