---
name: NPM Build
description: Set up Node environment and build a Node.js project

runs:
  using: composite
  steps:
    - name: Set Up Environment and load Cached Dependencies
      uses: catenaclearing/catena-actions/composite/setup-node@0

    - name: Build
      shell: bash
      run: npm run build
