---
name: Bump and Release to Protected Branch
description: Disable branch protection, bump and release a new version, then re-enable branch protection.

inputs:
  machine_user_pat:
    description: Github Catena Machine User Personal Access Token (PAT)
    required: true

  branch:
    description: Branch to bump and release
    required: false
    default: main

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v7

    - name: Temporarily disable "include administrators" branch protection
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.machine_user_pat }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ inputs.branch }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        "$ACTION_PATH/toggle-enforce-admins.sh" disable

    - name: Bump Version and Release
      uses: catenaclearing/catena-actions/actions/release@v0
      with:
        machine_user_pat: ${{ inputs.machine_user_pat }}

    - name: Enable "include administrators" branch protection
      if: always()
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.machine_user_pat }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ inputs.branch }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        "$ACTION_PATH/toggle-enforce-admins.sh" enable
