---
name: Update Mintlify Docs
description: Trigger a documentation update on Mintlify for the specified project and monitor progress.

inputs:
  mintlify_project_id:
    description: Mintlify Project ID
    required: true

  mintlify_token:
    description: Mintlify Assistant API Token
    required: true

  old_openapi_file:
    description: Path to the old/base OpenAPI specification file (JSON or YAML)
    required: true

  new_openapi_file:
    description: Path to the new/changed OpenAPI specification file (JSON or YAML)
    required: true

runs:
  using: docker
  image: Dockerfile
