---
name: Open Pull Request
description: Open a Pull Request from a feature branch to the main branch

inputs:
  title:
    description: Pull Request Title
    required: false

  template_file:
    description: Name of the pull request template file
    required: true
    default: WWHTDA.md

  machine_user_pat:
    description: Github Catena Machine User Personal Access Token (PAT)
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Create Pull Request
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ inputs.machine_user_pat }}
      run: |
        # Fallback to github.ref_name if inputs.title is empty
        if [ -z "${{ inputs.title }}" ]; then
          PR_TITLE="${{ github.ref_name }}"
        else
          PR_TITLE="${{ inputs.title }}"
        fi

        gh pr create \
          --title "$PR_TITLE" \
          --body-file "${{ github.action_path }}/templates/${{ inputs.template_file }}" \
          --base main \
          --draft
