---
name: Open Pull Request
description: Open a Pull Request from a feature branch to the main branch

inputs:
  title:
    description: Pull Request Title
    required: false

  template_file:
    description: Name of the pull request template file
    required: true
    default: WWHTDA.md

  machine_user_pat:
    description: Github Catena Machine User Personal Access Token (PAT)
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Create Pull Request
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ inputs.machine_user_pat }}
        INPUT_TITLE: ${{ inputs.title }}
        REF_NAME: ${{ github.ref_name }}
        ACTION_PATH: ${{ github.action_path }}
        TEMPLATE_FILE: ${{ inputs.template_file }}
      run: |
        # Fallback to github.ref_name if inputs.title is empty
        if [ -z "$INPUT_TITLE" ]; then
          PR_TITLE="$REF_NAME"
        else
          PR_TITLE="$INPUT_TITLE"
        fi

        gh pr create \
          --title "$PR_TITLE" \
          --body-file "$ACTION_PATH/templates/$TEMPLATE_FILE" \
          --base main \
          --draft
