---
name: Open Pull Request
description: Open a Pull Request from a feature branch to the main branch

inputs:
  title:
    description: Pull Request Title
    required: true

  template-file:
    description: Name of the pull request template file
    required: true
    default: WWHTDA.md

  github-token:
    description: GitHub Token
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Create Pull Request
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        gh pr create \
          --title "${{ inputs.title }}"  \
          --body-file "./actions/open-pull-request/templates/${{ inputs.template-file }}" \
          --base main \
          --draft
