---
name: Set Up Python Environment
description: Install Python and Poetry for Python projects

inputs:
  python_version:
    description: Python version
    required: false
    default: '3.13'

  poetry_version:
    description: Poetry version
    required: false
    default: '2.0.1'

  machine_user_pat:
    description: Github Catena Machine User Personal Access Token (PAT)
    required: true

runs:
  using: composite
  steps:
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.machine_user_pat }}

    - name: Configure git PAT to access our private repositories
      shell: bash
      run: git config --global url.https://${{ inputs.machine_user_pat }}@github.com/.insteadOf https://github.com/

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version ${{ inputs.poetry_version }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry
      shell: bash
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.path .venv
        poetry config cache-dir ~/.poetry/cache

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: poetry
