---
name: Set Up Python Environment
description: Install Python and Poetry for Python projects

inputs:
  python_version:
    description: Python version
    required: false
    default: '3.12'

  poetry_version:
    description: Poetry version
    required: false
    default: '2.0.1'

  machine_user_pat:
    description: Github Catena Machine User Personal Access Token (PAT)
    required: true

  directory:
    description: Directory to set up the Python environment. Useful for monorepos when there are multiple projects.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.machine_user_pat }}

    - name: Configure git PAT to access our private repositories
      shell: bash
      run: |
        git config --global url.https://${{ inputs.machine_user_pat }}@github.com/.insteadOf https://github.com/

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry_version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.directory }}/.venv
        key: >-
          venv-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-
          ${{ hashFiles(format('{0}/poetry.lock', inputs.directory)) }}

    - name: Install Dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        poetry config keyring.enabled false
        poetry install --no-interaction --no-root --sync --all-groups --all-extras
