---
name: Build Node

on:
  push:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  setup:
    name: Build Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Node project
        uses: catenaclearing/catena-actions/composite/build-node@main
        with:
          machine_user_pat: ${{ secrets.MACHINE_USER_PAT }}
