---
name: Setup Python and Poetry

on:
  push:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  setup:
    name: Setup Python and Poetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python Environment
        uses: catenaclearing/catena-actions/composite/setup-python@main
        with:
          machine_user_pat: ${{ secrets.MACHINE_USER_PAT }}
